version: '3.8'

services:
  web:
    restart: always
    build: .
    links:
      - postgres:postgres

    environment:
      DEBUG: False
      POSTGRES_DB: "cash_machine_db"  #Введите название базы данных postgres
      DATABASE_PORT: "5432"
      POSTGRES_USER: "postgres"  #Введите название пользователя базы данных
      POSTGRES_PASSWORD: "rtf558Ur" #Введите пароль пользователя базы данных
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: >
#      sh -c "python Cash_machine/manage.py migrations && python Cash_machine/manage.py runserver 0.0.0.0:8000"


  postgres:
    hostname: postgres
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "cash_machine_db"  #Введите название базы данных postgres
      POSTGRES_USER: "postgres"  #Введите название пользователя базы данных
      POSTGRES_PASSWORD: "rtf558Ur"  #Введите пароль пользователя базы данных
    ports:
      - "5432:5432"

volumes:
  db-data: